DROP TABLE IF EXISTS GiaoDich;
DROP TABLE IF EXISTS KhachHang;
DROP TABLE IF EXISTS SanPham;

-- ===== BẢNG SẢN PHẨM =====
CREATE TABLE SanPham (
  MaSP        VARCHAR(100) PRIMARY KEY,
  TenSP       VARCHAR(100) NOT NULL,
  GiaSP       DOUBLE NOT NULL,
  HinhAnhSP   VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== BẢNG KHÁCH HÀNG =====
CREATE TABLE KhachHang (
  MaKH    VARCHAR(100) PRIMARY KEY,
  TenKH   VARCHAR(100) NOT NULL,
  SDT     VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== BẢNG GIAO DỊCH =====
CREATE TABLE GiaoDich (
  TenSP     VARCHAR(100) NOT NULL,
  TenKH     VARCHAR(100) NOT NULL,
  SDTKH     VARCHAR(100),
  TongTien  DOUBLE NOT NULL,
  PRIMARY KEY (TenSP),
  CONSTRAINT fk_gd_sp FOREIGN KEY (TenSP) REFERENCES SanPham(TenSP),
  CONSTRAINT fk_gd_kh FOREIGN KEY (TenKH) REFERENCES KhachHang(TenKH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
